version: '3.3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: hackmoscow
      POSTGRES_PASSWORD: hackmoscow
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
  api:
    build: ./controller
    expose:
      - 1233
      - 7000
      - 6000
    ports:
      - 1233:1233
      - 7000:7000
      - 6000:6000
    restart: always
    depends_on:
      - db
